# This workflow automatically publishes the HAF and TFA binaries for a given
# release.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Hafnium and Trusted Firmware-A Build

on:
  release:
    types:
      - published
  pull_request:
    branches:
      - '**'  # Matches all branches
    paths:
      - '**'  # Matches all paths
  workflow_dispatch:

jobs:
  build:
    name: Hafnium and Trusted Firmware-A Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/microsoft/mu_devops/ubuntu-24-dev:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Pip Modules
        run: |
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Stuart Build and Run 
        uses: ./.github/actions/build-platform
        with:
          platform-config: 'Platforms/QemuSbsaPkg/PlatformBuild.py'
          platform-name: 'SBSA'
          tool-chain: 'GCC5'
          stuart-args: 'HAF_TFA_BUILD=TRUE'
          publish-logs: 'true'

      - name: Upload Firmware Binaries (artifacts)
        uses: actions/upload-artifact@v4
        with:
          # One artifact per matrix target so they don't overwrite each other
          name: haf-tfa-firmware
          if-no-files-found: error
          path: |
            Build/QemuSbsaPkg/DEBUG_GCC5/HafTfaBins/**
          retention-days: 14

  publish:
    name: Publish HAF/TFA Firmware Binaries
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/artifacts

      - name: Create per-target archives
        run: |
          set -euo pipefail
          cd "${RUNNER_TEMP}/artifacts"
          for d in */ ; do
            d="${d%/}"
            echo "Zipping $d ..."
            ( cd "$d" && zip -r "${RUNNER_TEMP}/${d}-${{ github.event.release.tag_name }}.zip" . )
            ( cd "$d" && tar -czf "${RUNNER_TEMP}/${d}-${{ github.event.release.tag_name }}.tar.gz" . )
          done
          echo "Done creating archives:"
          ls -lh "${RUNNER_TEMP}"/*.zip "${RUNNER_TEMP}"/*.tar.gz

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" "${RUNNER_TEMP}"/*.zip
          gh release upload "${{ github.event.release.tag_name }}" "${RUNNER_TEMP}"/*.tar.gz
